agent/urls.py
from django.urls import path
from . import views

app_name = "agent"

urlpatterns = [
    path('list.html', views.AgentListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.AgentDetailView.as_view(), name='detail'),
    path('register.html', views.AgentCreateView.as_view(), name='create'),
    path('create/success.html', views.success_agent_create, name='success_create'),

    path('update/<int:pk>/', views.AgentUpdateView.as_view(), name='update'),
]

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('list.html', views.PropertyListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.PropertyDetailView.as_view(), name='detail'),
    path('new/', views.PropertyCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.PropertyUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', views.PropertyDeleteView.as_view(), name='delete'),

    # inquiries
    path('query/new/', views.NewEnquiryView.as_view(), name='enquiry_new'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html', views.index, name='index_page'),
    path('', views.index, name='index_page'),
    path('about.html', views.about, name='about_page'),
    path('blog.html', views.blog, name='blog_page'),

    path('property/', include('property.urls')),
    path('agent/', include('agent.urls')),
    path('booking/', include('booking.urls')),
    path('contact/', include('contact.urls')),

    # for auth views
    path('auth/', include('django.contrib.auth.urls')),
]

# for serving media documents
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agent/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import os
from django.urls import reverse_lazy
from django.conf import settings


# Create your models here.
class Agent(models.Model) :
    telephone = models.IntegerField(verbose_name='Phone Number')
    address = models.CharField(verbose_name='Physical Address', max_length=200, null=True)
    description = models.TextField(verbose_name='Description')
    picture = models.ImageField(verbose_name='Picture', upload_to="agent")
    date_added = models.DateField(default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        if self.user.get_full_name() is not "" :
            return self.user.get_full_name()
        else:
            return self.user.username

    def get_absolute_url(self):
        return reverse_lazy('agent:detail', kwargs={'pk':self.pk})

agent/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Agent


class AgentForm(forms.ModelForm) :
    class Meta :
        exclude = ('date_added', )


class AgentCreationForm(forms.Form) :
    first_name = forms.CharField(label="First Name", required=True)
    last_name = forms.CharField(label="Last Name", required=True)
    password1 = forms.CharField(label="Password", required=True, widget=forms.PasswordInput, max_length=30)
    password2 = forms.CharField(label="Password Confirm", required=True, widget=forms.PasswordInput, max_length=30)
    email = forms.EmailField(label="Email address", required=True)

    telephone = forms.IntegerField(label="Telephone", required=True)
    description = forms.CharField(label="Description", required=True)
    picture = forms.ImageField(label="Picture", required=True)

    def clean(self):
        form_data = self.cleaned_data
        if form_data['password1'] != form_data.get('password2') :
            self.add_error("password1", "Passwords must match")
            self.add_error("password2", "Passwords must match")

            del form_data['password1']
            del form_data['password2']

        return form_data

    def save(self):
        user = User.objects.create_user(
            self.cleaned_data['email'],
            email=self.cleaned_data['email'],
            first_name=self.cleaned_data['first_name'],
            last_name= self.cleaned_data['last_name']
        )
        user.set_password(self.cleaned_data['password1'])
        user.save()

        agent = Agent.objects.create(
            user=user,
            telephone=self.cleaned_data['telephone'],
            description=self.cleaned_data['description'],
            picture=self.cleaned_data['picture']
        )
        agent.save()

        return agent

agent/views.py
from django.views.generic import ListView
from .models import Agent
from django.views.generic import FormView, DetailView
from django.views.generic.edit import UpdateView
from .forms import AgentCreationForm
from django.shortcuts import render
from django.urls import reverse_lazy


# Create your views here.
class AgentListView(ListView):
    model = Agent


class AgentUpdateView(UpdateView) :
    model = Agent
    template_name_suffix = 'update_form'
    fields = ('telephone', 'picture', 'description', 'address')


class AgentDetailView(DetailView) :
    model = Agent


class AgentCreateView(FormView):
    template_name = 'agent/agent_create_form.html'
    form_class = AgentCreationForm
    success_url = reverse_lazy('agent:success_create')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def success_agent_create(request):
    return render(request, 'agent/success_agent_create.html')

templates/agent/agent_create_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Register</span>
    <h2>Register</h2>
</div>
</div>
<!-- banner -->


<div class="container">
    <div class="spacer">
        <div class="row register">
            <div class="col-lg-6 col-lg-offset-3 col-sm-6 col-sm-offset-3 col-xs-12 ">
                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Register</button>
                    <button type="reset" class="btn btn-default">Reset</button>
                </form>

                {# Assumes you setup the password_reset view in your URLconf #}
                <p>
                    <a href="{% url 'password_reset' %}">Lost password?</a>
                    <a href="{% url 'login' %}" class="pull-right">Have an account?</a>
                </p>
            </div>
        </div>
    </div>
</div>
    <script src="{% static 'assets/js/form_script.js' %}"></script>
{% endblock %}

templates/agent/agent_detail.html
{% if agent.user == request.user %}
    <a href="{% url 'agent:update' agent.id %}">Update yor details</a>
{% endif %}

<br>
Name : {{ agent.user.get_full_name }}
<br>
Email : {{ agent.user.email }}
<br>
Telephone : {{ agent.telephone }}
<br>

<img src="{{ MEDIA_URL }}{{ agent.picture }}" alt="{{ agent }}" width="20%" height="auto"/>
<br>

<a href="{% url 'agent:list' %}">Click here to go back to agent list</a>

templates/agent/agent_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Agents</span>
    <h2>Agents</h2>
</div>
</div>
<!-- banner -->


<div class="container">
<div class="spacer agents">

<div class="row">
  <div class="col-lg-8  col-lg-offset-2 col-sm-12">

      {% for agent in agent_list %}
          {#      agent item#}
          <div class="row">
            <div class="col-lg-2 col-sm-2 "><a href="#"><img src="{{ MEDIA_URL }}{{ agent.picture }}" class="img-responsive" alt="{{ agent.user.get_full_name }}"></a></div>
            <div class="col-lg-7 col-sm-7 ">
                <h4><a href="{% url 'agent:detail' agent.pk %}">{{ agent.user.get_full_name }}</a> </h4>
                <p>{{ agent.description }}</p>
            </div>
            <div class="col-lg-3 col-sm-3 "><span class="glyphicon glyphicon-envelope"></span> <a href="mailto:{{ agent.user.email }}">{{ agent.user.email }}</a><br>
            <span class="glyphicon glyphicon-earphone"></span> {{ agent.telephone }}</div>
        </div>
          {#      end of agent item#}
      {% endfor %}


  </div>
</div>


</div>
</div>

{% endblock %}

templates/agent/agentupdate_form.html
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
    <input type="reset" value="Reset">
</form>

templates/agent/success_agent_create.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="row panel">
        <div class="panel-heading">
            <h3 class="text-success">Success</h3>
        </div>
        <div class="panel-body">
            <h4>
                Your profile has been registred successfully! <a href="{% url 'property:list' %}">Click here to view or add  properties</a>
            </h4>
        </div>
    </div>
    </div>

{% endblock %}