agent/urls.py
from django.urls import path
from . import views

app_name = "agent"

urlpatterns = [
    path('list.html', views.AgentListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.AgentDetailView.as_view(), name='detail'),
    path('register.html', views.AgentCreateView.as_view(), name='create'),
    path('create/success.html', views.success_agent_create, name='success_create'),

    path('update/<int:pk>/', views.AgentUpdateView.as_view(), name='update'),
]

booking/urls.py
from django.urls import path
from . import views

app_name = "booking"

urlpatterns = [
    path('new.html', views.NewBooking.as_view(), name='booking_new'),
    path('new/<int:property_id>/', views.SelectedBookingView.as_view(), name='booking_selected'),
    path('new/success.html', views.success_booking, name='success_new'),
    path('list.html/', views.BookingList.as_view(), name="list"),
]

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('list.html', views.PropertyListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.PropertyDetailView.as_view(), name='detail'),
    path('new/', views.PropertyCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.PropertyUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', views.PropertyDeleteView.as_view(), name='delete'),

    # inquiries
    path('query/new/', views.NewEnquiryView.as_view(), name='enquiry_new'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html', views.index, name='index_page'),
    path('', views.index, name='index_page'),
    path('about.html', views.about, name='about_page'),
    path('blog.html', views.blog, name='blog_page'),

    path('property/', include('property.urls')),
    path('agent/', include('agent.urls')),
    path('booking/', include('booking.urls')),
    path('contact/', include('contact.urls')),

    # for auth views
    path('auth/', include('django.contrib.auth.urls')),
]

# for serving media documents
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

property/models.py
from django.db import models
from django.utils import timezone
from agent.models import Agent
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth.models import User
import os


# Create your models here.
class SaleType(models.Model) :
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        ordering = ("name", )
        verbose_name = "Type of Sale"
        verbose_name_plural = "Types of Sale"

    def __str__(self):
        return self.name


class BuildingType(models.Model) :
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta :
        verbose_name = "Type of Building"
        verbose_name_plural = "Types of Building"
        ordering = ("name", )


class Property(models.Model) :
    name = models.CharField(max_length=100)
    agent = models.ForeignKey(Agent, on_delete=models.SET_NULL, null=True, verbose_name='Agent')
    price = models.FloatField(verbose_name='Property Price')
    description = models.TextField(verbose_name='Property Details')
    location = models.CharField(max_length=200, verbose_name='Property Location')
    building_type = models.ForeignKey(BuildingType, on_delete=models.SET_NULL, null=True, verbose_name='Property Type')
    sale_type = models.ForeignKey(SaleType, on_delete=models.SET_NULL, null=True, verbose_name='Type of Sale')
    date_added = models.DateField(default=timezone.now, verbose_name='Date Registered')
    bedrooms = models.IntegerField(default=0, verbose_name='Number of Bedrooms')
    kitchens = models.IntegerField(default=0, verbose_name='Number of Kitchens')
    living_rooms = models.IntegerField(default=0, verbose_name='Number of Living Rooms')
    parking = models.IntegerField(default=0, verbose_name='Number of Parking Lots')
    picture_1 = models.ImageField(upload_to="media/property")
    picture_2 = models.ImageField(blank=True, null=True, upload_to="media/property")
    picture_3 = models.ImageField(blank=True, null=True, upload_to="media/property")
    picture_4 = models.ImageField(blank=True, null=True, upload_to="media/property")
    availability = models.BooleanField(default=True)

    class Meta :
        verbose_name_plural = 'Properties'
        ordering =['name', 'price']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse_lazy('property:detail', kwargs={'pk':self.pk})


class PropertyEnquiry(models.Model) :
    property = models.ForeignKey(Property, on_delete=models.CASCADE, verbose_name="Property Details")
    user = models.ForeignKey(User,on_delete=models.CASCADE, verbose_name="Customer")
    subject = models.CharField(max_length=200)
    message = models.TextField(verbose_name="Customer Message")
    date = models.DateTimeField(default=timezone.now)

    class Meta :
        verbose_name = "Property Inquiry"
        verbose_name_plural = "Property Inquiries"
        ordering = ['date', 'property']

property/forms.py
from  django import forms
from property.models import PropertyEnquiry


class PropertyForm (forms.ModelForm) :
    class Meta :
        exclude = ('date_added',)


class PropertyTypeForm(forms.ModelForm) :
    class Meta :
        exclude = ()


class EnquiryForm(forms.Form) :
    subject = forms.CharField(required=True, )
    message = forms.CharField(required=True, widget=forms.Textarea)

    def save_inquiry(self, user, property):
        inquiry = PropertyEnquiry.objects.create(
            user=user,
            property=property,
            message=self.data['message'],
            subject=self.data['subject'],
        )
        inquiry.save()

property/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView, DetailView, DeleteView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Property, PropertyEnquiry
from django.urls import reverse_lazy
from agent.models import Agent
from django.shortcuts import redirect
from .forms import EnquiryForm


# Create your views here.
def hot_properties(number):
    property_list = Property.objects.filter(availability=True)[:number]
    return property_list


class PropertyCreateView(LoginRequiredMixin, CreateView):
    template_name_suffix = '_create_form'
    model = Property
    fields = (
        'name', 'price', 'location', 'description', 'building_type', 'sale_type', 'bedrooms', 'kitchens',
        'living_rooms', 'parking', \
        'picture_1', 'picture_2', 'picture_3', 'picture_4')

    def form_valid(self, form):
        agent = Agent.objects.get(user=self.request.user)
        self.object = form.save()
        self.object.agent = agent
        self.object.save()
        return redirect(reverse_lazy("property:detail", kwargs={'pk':self.object.id}))


class PropertyDeleteView(DeleteView):
    model = Property


class PropertyUpdateView(UpdateView):
    template_name_suffix = '_update_form'
    model = Property
    fields = (
        'name', 'price', 'description', 'location', 'building_type', 'sale_type', 'bedrooms', 'kitchens',
        'living_rooms', 'parking', \
        'picture_1', 'picture_2', 'picture_3', 'picture_4')
    # success_url = reverse_lazy('property:success_update')


class PropertyDetailView(DetailView):
    model = Property
    extra_context = {
        'hot_property_list': hot_properties(4)
    }


class PropertyListView(ListView):
    paginate_by = 10
    extra_context = {
        'hot_property_list': hot_properties(4)
    }

    def get_queryset(self):
        name = self.request.GET.get("name")
        building_type = self.request.GET.get("building_type")
        sale_type = self.request.GET.get("sale_type")
        min_price = self.request.GET.get("min")
        max_price = self.request.GET.get("max")

        property_list = Property.objects.all()

        if name is not None:
            property_list = property_list.filter(name__icontains=name)
        if sale_type is not None :
            property_list = property_list.filter(sale_type=sale_type)
        if building_type is not None:
            property_list = property_list.filter(property_type=building_type)
        if min_price is not None and min_price is not "":
            property_list = property_list.filter(price__gte=float(min_price))
        if max_price is not None and max_price is not "":
            property_list = property_list.filter(price__lte=float(max_price))
        return property_list

    model = Property


class NewEnquiryView(LoginRequiredMixin, FormView):
    form_class = EnquiryForm
    template_name = 'property/propertyenquiry_form.html'

    def get_success_url(self):
        return reverse_lazy('property:detail', kwargs={'pk':self.kwargs['property_id']})

    def form_valid(self, form):
        property = Property.objects.get(pk=self.kwargs['property_id'])
        form.save_inquiry(self.request.user, property=property)
        return super(NewEnquiryView, self).form_valid(form)


class InquiryDetail(DetailView) :
    model = PropertyEnquiry

templates/property/property_create_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Property/ Create</span>
    <h2>Add a property</h2>
</div>
</div>
<!-- banner -->


<div class="container">
    <div class="spacer">
        <div class="row register">
            <div class="col-lg-6 col-lg-offset-3 col-sm-6 col-sm-offset-3 col-xs-12 ">

                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="submit" class="btn btn-success">Submit</button>
                    <button type="reset" value="Reset" class="btn btn-info"> Reset </button>
                </form>

            </div>
        </div>
    </div>
</div>
    <script src="{% static 'assets/js/form_script.js' %}"></script>
{% endblock %}

templates/property/property_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Buy</span>
    <h2>Buy</h2>
</div>
</div>
<!-- banner -->


<div class="container">
<div class="properties-listing spacer">

<div class="row">
<div class="col-lg-3 col-sm-4 hidden-xs">

<div class="hot-properties hidden-xs">
<h4>Hot Properties</h4>
    {% for property in hot_property_list %}
        <div class="row">
            <div class="col-lg-4 col-sm-5">
                <img src="{{ MEDIA_URL }}{{ property.picture_1 }}" class="img-responsive img-circle" alt="{{ property.name }}"/>
            </div>
            <div class="col-lg-8 col-sm-7">
                <h5><a href="{% url 'property:detail' property.id %}">{{ property.name }}</a></h5>
                <p class="price">${{ property.price }}</p>
            </div>
        </div>
    {% endfor %}

</div>


</div>

<div class="col-lg-9 col-sm-8 ">

<h2>{{ property.name }}</h2>
<div class="row">
  <div class="col-lg-8">
  <div class="property-images">
    <!-- Slider Starts -->
<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators hidden-xs">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        <li data-target="#myCarousel" data-slide-to="3" class=""></li>
      </ol>
      <div class="carousel-inner">
        <!-- Item 1 -->
        <div class="item active">
          <img src="{{ MEDIA_URL }}{{ property.picture_1 }}" class="properties" alt="{{ property.name }}" />
        </div>
        <!-- #Item 1 -->

        <!-- Item 2 -->
        <div class="item">
          <img src="{{ MEDIA_URL }}{{ property.picture_2 }}" class="properties" alt="{{ property.name }}" />

        </div>
        <!-- #Item 2 -->

        <!-- Item 3 -->
         <div class="item">
          <img src="{{ MEDIA_URL }}{{ property.picture_3 }}" class="properties" alt="{{ property.name }}" />
        </div>
        <!-- #Item 3 -->

        <!-- Item 4 -->
        <div class="item ">
          <img src="{{ MEDIA_URL }}{{ property.picture_4 }}" class="properties" alt="{{ property.name }}" />

        </div>
        <!-- # Item 4 -->
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
<!-- #Slider Ends -->

  </div>




  <div class="spacer">
      <h4> <span class="glyphicon glyphicon-th-list"></span> Properties Detail </h4>
      {% if property.availability %}
          <span class="text-success">Available</span>
      {% else %}
          <span class="text-warning">{{ property.sale_type }} Out</span>
      {% endif %}
      <p> {{ property.description }} </p>

  </div>

  </div>
  <div class="col-lg-4">
  <div class="col-lg-12  col-sm-6">
    <div class="property-info">
        <p class="price">
            $ {{ property.price }}
            {% if request.user.is_authenticated %}
                {% if request.user == property.agent.user %}
                    <button class="btn btn-default"><a href="{% url 'property:update' property.id %}" class="btn btn-info">Edit property</a></button>
                {% endif %}
                    <button class="btn btn-default"><a href="{% url 'booking:booking_selected' property.id %}">Book Property</a></button>
            {% endif %}

        </p>
        <p class="area"><span class="glyphicon glyphicon-map-marker"></span> {{ property.location }}</p>

        <div class="profile">
            <span class="glyphicon glyphicon-user"></span> Agent Details
            <p>{{ property.agent.user.get_full_name }}<br>{{ property.agent.telephone }}</p>
        </div>
    </div>

    <h6><span class="glyphicon glyphicon-home"></span> Availabilty</h6>
    <div class="listing-detail">
    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Bed Room">5</span> <span data-toggle="tooltip" data-placement="bottom" data-original-title="Living Room">2</span> <span data-toggle="tooltip" data-placement="bottom" data-original-title="Parking">2</span> <span data-toggle="tooltip" data-placement="bottom" data-original-title="Kitchen">1</span> </div>

  </div>
<div class="col-lg-12 col-sm-6 ">
<div class="enquiry">
  <h6><span class="glyphicon glyphicon-envelope"></span> Post Enquiry</h6>
  <form role="form" action="{% url 'property:enquiry_new' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="property" value="{{ property.id }}" />
      <input type="text" class="form-control" placeholder="Full Name" name="name" required=""/>
      <input type="email" class="form-control" placeholder="you@yourdomain.com" name="email" required=""/>
      <input type="text" class="form-control" placeholder="your number" name="telephone" required=""/>
      <textarea rows="6" class="form-control" placeholder="Whats on your mind?" name="message" required=""></textarea>
      <button type="submit" class="btn btn-primary" name="Submit">Send Message</button>
      </form>
 </div>
</div>
  </div>
</div>
</div>
</div>
</div>
</div>
{% endblock %}

templates/property/property_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Buy, Sale & Rent</span>
    <h2>Buy, Sale & Rent</h2>
</div>
</div>
<!-- banner -->


<div class="container">
<div class="properties-listing spacer">

<div class="row">
<div class="col-lg-3 col-sm-4 ">
    {% if request.user.is_authenticated %}
        <div style="padding: 20px">
        <button class="btn btn-default"><a href="{% url 'property:create' %}">Register Property</a></button>
        </div>
    {% endif %}
  <div class="search-form"><h4><span class="glyphicon glyphicon-search"></span> Search for</h4>
    <form method="get" action="{% url 'property:list' %}">
            <input type="text" class="form-control" placeholder="Name of Properties" name="name">
    <div class="row">
            <div class="col-lg-6">
              <input type="number" class="form-control" placeholder="Minimum" name="min"/>
            </div>
            <div class="col-lg-6">
              <input type="number" class="form-control" placeholder="Maximum" name="max">
            </div>
          </div>

          <div class="row">
          <div class="col-lg-12">
              <select class="form-control" name="building_type">
                  {% for type in property_building_type_list  %}
                      <option value="{{ type.id }}">{{ type.name }}</option>
                  {% endfor %}
              </select>
              </div>
          </div>
          <button class="btn btn-primary" type="submit">Find Now</button>

    </form>

  </div>

    <div class="hot-properties hidden-xs">
        <h4>Hot Properties</h4>
{#        hot property list#}
        {% for property in hot_property_list %}
            <div class="row">
                <div class="col-lg-4 col-sm-5">
                    <img src="{{ MEDIA_URL }}{{ property.picture_1 }}" class="img-responsive img-circle" alt="properties">
                </div>
                <div class="col-lg-8 col-sm-7">
                <h5><a href="{% url 'property:detail' property.id %}">{{ property.name }}</a></h5>
                <p class="price">${{ property.price }}</p> </div>
            </div>
        {% endfor %}

{#        end hot property list#}

    </div>


</div>

<div class="col-lg-9 col-sm-8">
<div class="sortby clearfix">
{#<div class="pull-left result">Showing: 12 of 100 </div>#}
  <div class="pull-right">
  <select class="form-control">
  <option>Sort by</option>
  <option>Price: Low to High</option>
  <option>Price: High to Low</option>
</select></div>

</div>
<div class="row">

    {#    individual property#}
    {% for property in property_list %}
        <div class="col-lg-4 col-sm-6">
        <div class="properties">
            <div class="image-holder"><img src="{{ MEDIA_URL }}{{ property.picture_1 }}" class="img-responsive" alt="{{ property.name }}">
                <div class="status sold">
                    {% if property.availability %}
                        Available
                    {% else %}
                        Sold
                    {% endif %}
                </div>
            </div>
        <h4><a href="{% url 'property:detail' property.id %}">{{ property.name }}</a></h4>
        <p class="price">Price: {{ property.price }}</p>
        <div class="listing-detail">
            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Bed Room">{{ property.bedrooms }}</span>
            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Living Room">{{ property.living_rooms }}</span>
            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Parking">{{ property.parking }}</span>
            <span data-toggle="tooltip" data-placement="bottom" data-original-title="Kitchen">{{ property.kitchens }}</span>
        </div>
        <a class="btn btn-primary" href="{% url 'property:detail' property.id %}">View Details</a>
      </div>
      </div>
    {% endfor %}
    {#    end of individual property#}

</div>
</div>
</div>
</div>
</div>
{% endblock %}

templates/property/property_update_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Property/ Edit</span>
    <h2>Edit property {{ property.name }}</h2>
</div>
</div>
<!-- banner -->


<div class="container">
    <div class="spacer">
        <div class="row register">
            <div class="col-lg-6 col-lg-offset-3 col-sm-6 col-sm-offset-3 col-xs-12 ">

                <form method="post" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" value="submit" class="btn btn-success">Submit</button>
                    <button type="reset" value="Reset" class="btn btn-info"> Reset </button>
                </form>

            </div>
        </div>
    </div>
</div>
    <script src="{% static 'assets/js/form_script.js' %}"></script>
{% endblock %}

templates/property/propertyenquiry_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Property/ Enquiry</span>
    <h2>Enquiry Details</h2>
</div>
</div>
<!-- banner -->


<div class="container">
    <div class="spacer">
        <div class="row">
            <table class="table">
                <thead>
                    <td>Property</td>
                    <td></td>
                </thead>
                <tr>
                    <td>{{ propertyenquiry.property }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
    <script src="{% static 'assets/js/form_script.js' %}"></script>
{% endblock %}

templates/property/propertyenquiry_form.html
<h3> New Query</h3>

<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="submit">Submit</button>
    <button type="reset" value="Reset"> Reset </button>
</form>