agent/urls.py
from django.urls import path
from . import views

app_name = "agent"

urlpatterns = [
    path('list.html', views.AgentListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.AgentDetailView.as_view(), name='detail'),
    path('register.html', views.AgentCreateView.as_view(), name='create'),
    path('create/success.html', views.success_agent_create, name='success_create'),

    path('update/<int:pk>/', views.AgentUpdateView.as_view(), name='update'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns =[
    path('index.html/', views.contact_page, name='contact_page'),

    path('question/list.html', views.QuestionListView.as_view(), name='question_list'),
    path('question/new.html', views.NewQuestionView.as_view(), name='question_create'),
    path('question/new/success.html', views.success_question_create, name='success_question_create'),

    path('tag/list/html', views.TagListView.as_view(), name='tag_list'),
    path('tag/new.html', views.NewQuetionTagView.as_view(), name='tag_create'),
    path('tag/new/success.html', views.success_tag_create, name='success_tag_new'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html', views.index, name='index_page'),
    path('', views.index, name='index_page'),
    path('about.html', views.about, name='about_page'),
    path('blog.html', views.blog, name='blog_page'),

    path('property/', include('property.urls')),
    path('agent/', include('agent.urls')),
    path('booking/', include('booking.urls')),
    path('contact/', include('contact.urls')),

    # for auth views
    path('auth/', include('django.contrib.auth.urls')),
]

# for serving media documents
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class QuestionTag(models.Model) :
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        verbose_name = "Question Tag"
        verbose_name_plural = "Question Tags"
        ordering = ('name', 'description')

    def __str__(self):
        return self.name


class Question(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    tags = models.ManyToManyField(QuestionTag, related_name="Tags")
    time = models.DateTimeField(default=timezone.now)

    class Meta :
        verbose_name = "Contact Question"
        verbose_name_plural = "Contact Questions"
        ordering = ('name', 'subject')

    def __str__(self):
        return self.name

contact/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import QuestionTag, Question
from django.urls import reverse_lazy


# Create your views here.
def contact_page(request, *args, **kwargs):
    return render(request, 'contact/contact.html')


class NewQuestionView(CreateView):
    model = Question
    fields = ('name', 'email', 'message', 'subject')
    success_url = reverse_lazy('contact:contact_page')


class NewQuetionTagView(CreateView):
    model = QuestionTag


class QuestionListView(ListView):
    model = Question
    paginate_by = 10
    queryset = Question.objects.all()


class TagListView(ListView):
    model = QuestionTag
    queryset = QuestionTag.objects.all()
    paginate_by = 10


def success_question_create(request, *args, **kwargs) :
    return render(request, )


def success_tag_create(request, *args, **kwargs):
    return render(request, )

templates/contact/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Contact Us</span>
    <h2>Contact Us</h2>
      {% if request.user.is_staff %}
          <a href="{% url 'contact:question_list' %}">View all queries</a>
      {% endif %}
</div>
</div>
<!-- banner -->


<div class="container">
<div class="spacer">
<div class="row contact">
  <div class="col-lg-6 col-sm-6 ">

      <form class="form" action="{% url 'contact:question_create' %}" method="post">
            {% csrf_token %}
            <input type="text" class="form-control" placeholder="Full Name" name="name">
            <input type="text" class="form-control" placeholder="Email Address" name="email">
            <input type="text" class="form-control" placeholder="Subject" name="subject">
            <textarea rows="6" class="form-control" placeholder="Message" name="message"></textarea>
            <button type="submit" class="btn btn-success" name="Submit">Send Message</button>
      </form>
  </div>
  <div class="col-lg-6 col-sm-6 ">
    <div class="well">
        <iframe width="100%" height="300" frameborder="0" scrolling="no"
                marginheight="0" marginwidth="0"
                src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Pulchowk,+Patan,+Central+Region,+Nepal&amp;aq=0&amp;oq=pulch&amp;sll=37.0625,-95.677068&amp;sspn=39.371738,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=Pulchowk,+Patan+Dhoka,+Patan,+Bagmati,+Central+Region,+Nepal&amp;ll=27.678236,85.316853&amp;spn=0.001347,0.002642&amp;t=m&amp;z=14&amp;output=embed">
        </iframe>
    </div>
  </div>
</div>
</div>
</div>

{% endblock %}

templates/contact/question_form.html
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
    <input type="reset" value="Reset">
</form>

templates/contact/question_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Contact</span>
    <h2>Contact Queries</h2>
</div>
</div>
<!-- banner -->


<div class="container">
    <div class="spacer">
        <div class="row">
            <table class="table table-striped">
                <thead>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Subject</th>
                </thead>
                {% for question in question_list %}
                    <tr>
                        <td>{{ question.name }}</td>
                        <td>{{ question.email }}</td>
                        <td>{{ question.subject }}</td>
                    </tr>
                {% endfor %}

                <thead>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Subject</th>
                </thead>
            </table>
        </div>
    </div>
</div>
    <script src="{% static 'assets/js/form_script.js' %}"></script>
{% endblock %}

templates/contact/questiontag_form.html
<form method="post" action="">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
    <input type="reset" value="Reset">
</form>

templates/contact/success_question_create.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="row panel">
        <div class="panel-heading">
            <h3 class="text-success">Success</h3>
        </div>
        <div class="panel-body">
            <h4>
                Question places successfully. <a href="{% url 'contact:contact_page' %}">Click here to return to contact page.</a>
            </h4>
        </div>
    </div>
    </div>

{% endblock %}

templates/contact/success_tag_create.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
    <div class="row panel">
        <div class="panel-heading">
            <h3 class="text-success">Success</h3>
        </div>
        <div class="panel-body">
            <h4>
                Question tag added successfully. <a href="{% url 'contact:tag_list' %}">Click here to return to view all atgs.</a>

            </h4>
        </div>
    </div>
    </div>

{% endblock %}