agent/urls.py
from django.urls import path
from . import views

app_name = "agent"

urlpatterns = [
    path('list.html', views.AgentListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.AgentDetailView.as_view(), name='detail'),
    path('register.html', views.AgentCreateView.as_view(), name='create'),
    path('create/success.html', views.success_agent_create, name='success_create'),

    path('update/<int:pk>/', views.AgentUpdateView.as_view(), name='update'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns =[
    path('index.html/', views.contact_page, name='contact_page'),

    path('question/list.html', views.QuestionListView.as_view(), name='question_list'),
    path('question/new.html', views.NewQuestionView.as_view(), name='question_create'),
    path('question/new/success.html', views.success_question_create, name='success_question_create'),

    path('tag/list/html', views.TagListView.as_view(), name='tag_list'),
    path('tag/new.html', views.NewQuetionTagView.as_view(), name='tag_create'),
    path('tag/new/success.html', views.success_tag_create, name='success_tag_new'),
]

property/urls.py
from django.urls import path
from . import views

app_name = 'property'

urlpatterns = [
    path('list.html', views.PropertyListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.PropertyDetailView.as_view(), name='detail'),
    path('new/', views.PropertyCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.PropertyUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', views.PropertyDeleteView.as_view(), name='delete'),

    # inquiries
    path('query/new/', views.NewEnquiryView.as_view(), name='enquiry_new'),
]

real_estate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index.html', views.index, name='index_page'),
    path('', views.index, name='index_page'),
    path('about.html', views.about, name='about_page'),
    path('blog.html', views.blog, name='blog_page'),

    path('property/', include('property.urls')),
    path('agent/', include('agent.urls')),
    path('booking/', include('booking.urls')),
    path('contact/', include('contact.urls')),

    # for auth views
    path('auth/', include('django.contrib.auth.urls')),
]

# for serving media documents
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class QuestionTag(models.Model) :
    name = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        verbose_name = "Question Tag"
        verbose_name_plural = "Question Tags"
        ordering = ('name', 'description')

    def __str__(self):
        return self.name


class Question(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    tags = models.ManyToManyField(QuestionTag, related_name="Tags")
    time = models.DateTimeField(default=timezone.now)

    class Meta :
        verbose_name = "Contact Question"
        verbose_name_plural = "Contact Questions"
        ordering = ('name', 'subject')

    def __str__(self):
        return self.name

contact/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import QuestionTag, Question
from django.urls import reverse_lazy


# Create your views here.
def contact_page(request, *args, **kwargs):
    return render(request, 'contact/contact.html')


class NewQuestionView(CreateView):
    model = Question
    fields = ('name', 'email', 'message', 'subject')
    success_url = reverse_lazy('contact:contact_page')


class NewQuetionTagView(CreateView):
    model = QuestionTag


class QuestionListView(ListView):
    model = Question
    paginate_by = 10
    queryset = Question.objects.all()


class TagListView(ListView):
    model = QuestionTag
    queryset = QuestionTag.objects.all()
    paginate_by = 10


def success_question_create(request, *args, **kwargs) :
    return render(request, )


def success_tag_create(request, *args, **kwargs):
    return render(request, )

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / About Us</span>
    <h2>About Us</h2>
</div>
</div>
<!-- banner -->


<div class="container">
<div class="spacer">
<div class="row">
  <div class="col-lg-8  col-lg-offset-2">
  <img src="{% static 'images/about.jpg' %}" class="img-responsive thumbnail"  alt="realestate">
  <h3>Business Background</h3>
  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
  <h3>Company Profile</h3>
  <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
  <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
  </div>

</div>
</div>
</div>


{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ custom_site_name }} </title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="author" content="{{ custom_site_author }}" />
    <meta name="keywords" content="{{ custom_site_keywords }}" />

 	<link rel="stylesheet" href="{% static '/' %}assets/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="{% static '/' %}assets/style.css"/>
{#    revert back to cdn version #}
{#    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>#}
    <script src="{% static '/' %}assets/jquery/jquery.js"></script>
	<script src="{% static '/' %}assets/bootstrap/js/bootstrap.js"></script>
    <script src="{% static '/' %}assets/script.js"></script>

    <!-- Owl stylesheet -->
    <link rel="stylesheet" href="{% static '/' %}assets/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="{% static '/' %}assets/owl-carousel/owl.theme.css">
    <script src="{% static '/' %}assets/owl-carousel/owl.carousel.js"></script>
    <!-- Owl stylesheet -->


    <!-- slitslider -->
    <link rel="stylesheet" type="text/css" href="{% static '/' %}assets/slitslider/css/style.css" />
    <link rel="stylesheet" type="text/css" href="{% static '/' %}assets/slitslider/css/custom.css" />
    <script type="text/javascript" src="{% static '/' %}assets/slitslider/js/modernizr.custom.79639.js"></script>
    <script type="text/javascript" src="{% static '/' %}assets/slitslider/js/jquery.ba-cond.min.js"></script>
    <script type="text/javascript" src="{% static '/' %}assets/slitslider/js/jquery.slitslider.js"></script>
    <!-- slitslider -->

</head>
<body>


<!-- Header Starts -->
<div class="navbar-wrapper">

        <div class="navbar-inverse" role="navigation">
          <div class="container">
            <div class="navbar-header">


              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>


            <!-- Nav Starts -->
            <div class="navbar-collapse  collapse">
              <ul class="nav navbar-nav navbar-right">
               <li><a href="{% url 'index_page' %}">Home</a></li>
                <li><a href="{% url 'about_page' %}">About</a></li>
                <li><a href="{% url 'agent:list' %}">Agents</a></li>
                <li><a href="{% url 'blog_page' %}">Blog</a></li>
                <li><a href="{% url 'contact:contact_page' %}">Contact</a></li>
                  {% if request.user.is_authenticated %}
                      <li> <a href="{% url 'logout' %}">{{ request.user.get_full_name }} Logout</a> </li>
                  {% else %}
                      <li> <a href="{% url 'login' %}">Login</a> </li>
                  {% endif %}
              </ul>
            </div>
            <!-- #Nav Ends -->

          </div>
        </div>

    </div>
<!-- #Header Starts -->





<div class="container">

<!-- Header Starts -->
<div class="header">
<a href="{% url 'index_page' %}"><img src="{% static '/' %}images/logo.png" alt="{{ custom_site_name }}"></a>

              <ul class="pull-right">
                  {% for type in property_sale_type_list %}
                      <li><a href="{% url 'property:list' %}?sale_type={{ type.id }}">{{ type }}</a></li>
                  {% endfor %}
              </ul>
</div>
<!-- #Header Starts -->
</div>

{% block content %}
{% endblock %}




<div class="footer">

<div class="container">



<div class="row">
            <div class="col-lg-3 col-sm-3">
                   <h4>Information</h4>
                   <ul class="row">
                <li class="col-lg-12 col-sm-12 col-xs-3"><a href="{% url 'about_page' %}">About</a></li>
                <li class="col-lg-12 col-sm-12 col-xs-3"><a href="{% url 'agent:list' %}">Agents</a></li>
                <li class="col-lg-12 col-sm-12 col-xs-3"><a href="{% url 'blog_page' %}">Blog</a></li>
                <li class="col-lg-12 col-sm-12 col-xs-3"><a href="{% url 'contact:contact_page' %}">Contact</a></li>
              </ul>
            </div>

            <div class="col-lg-3 col-sm-3">
                    <h4>Newsletter</h4>
                    <p>Get notified about the latest properties in our marketplace.</p>
                    <form class="form-inline" role="form">
                            <input type="text" placeholder="Enter Your email address" class="form-control">
                                <button class="btn btn-success" type="button">Notify Me!</button></form>
            </div>

            <div class="col-lg-3 col-sm-3">
                    <h4>Follow us</h4>
                    <a href="#"><img src="{% static '/' %}images/facebook.png" alt="facebook"></a>
                    <a href="#"><img src="{% static '/' %}images/twitter.png" alt="twitter"></a>
                    <a href="#"><img src="{% static '/' %}images/linkedin.png" alt="linkedin"></a>
                    <a href="#"><img src="{% static '/' %}images/instagram.png" alt="instagram"></a>
            </div>

             <div class="col-lg-3 col-sm-3">
                    <h4>Contact us</h4>
                    <p><b>{{ custom_site_name }}.</b><br>
                    <span class="glyphicon glyphicon-map-marker"></span> {{ custom_site_address }} <br>
                    <span class="glyphicon glyphicon-envelope"></span>  {{ custom_site_email }} <br>
                    <span class="glyphicon glyphicon-earphone"></span> {{ custom_site_telephone }}</p>
            </div>
        </div>
<p class="copyright">Copyright 2018. All rights reserved.	</p>


</div></div>




<!-- Modal -->
<div id="loginpop" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="row">
        <div class="col-sm-6 login">
        <h4>Login</h4>
          <form class="" role="form" method="post" action="{% url 'login' %}">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ next }}" />
            <div class="form-group">
                <label class="sr-only" for="id_username">Email address</label>
                <input type="text" class="form-control" id="id_username" placeholder="Enter username" name="username">
            </div>
            <div class="form-group">
                <label class="sr-only" for="password">Password</label>
                <input type="password" class="form-control" id="id_password" placeholder="Password" name="password">
            </div>
            <div class="checkbox">
                <label><input type="checkbox"> Remember me</label>
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div>
        <div class="col-sm-6">
          <h4>New User Sign Up</h4>
          <p>Join today and get updated with all the properties deal happening around.</p>
          <button type="submit" class="btn btn-info"  onclick="window.location.href='{% url 'agent:create' %}'">Join Now</button>
        </div>

      </div>
    </div>
  </div>
</div>
<!-- /.modal -->



</body>
</html>

templates/blog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Blogs</span>
    <h2>Blogs</h2>
</div>
</div>
<!-- banner -->


<div class="container">
<div class="spacer blog">
<div class="row">
  <div class="col-lg-8 col-sm-12 ">

  <!-- blog list -->
  <div class="row">
                            <div class="col-lg-4 col-sm-4 "><a href="blogdetail.php" class="thumbnail"><img src="images/blog/4.jpg" alt="blog title"></a></div>
                            <div class="col-lg-8 col-sm-8 ">
                            <h3><a href="blogdetail.php">Creative business to takeover the market</a></h3>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                            <a href="blogdetail.php" class="more">Read More</a>
                            </div>
  </div>
  <!-- blog list -->


<!-- blog list -->
  <div class="row">
                            <div class="col-lg-4 col-sm-4 "><a href="blogdetail.php" class="thumbnail"><img src="images/blog/2.jpg" alt="blog title"></a></div>
                            <div class="col-lg-8 col-sm-8 ">
                            <h3><a href="blogdetail.php">Creative business to takeover the market</a></h3>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                            <a href="blogdetail.php" class="more">Read More</a>
                            </div>
  </div>
  <!-- blog list -->


  <!-- blog list -->
  <div class="row">
                            <div class="col-lg-4 col-sm-4 "><a href="blogdetail.php" class="thumbnail"><img src="images/blog/1.jpg" alt="blog title"></a></div>
                            <div class="col-lg-8 col-sm-8 ">
                            <h3><a href="blogdetail.php">Creative business to takeover the market</a></h3>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                            <a href="blogdetail.php" class="more">Read More</a>
                            </div>
  </div>
  <!-- blog list -->


  <!-- blog list -->
  <div class="row">
                            <div class="col-lg-4 col-sm-4 "><a href="blogdetail.php" class="thumbnail"><img src="images/blog/4.jpg" alt="blog title"></a></div>
                            <div class="col-lg-8 col-sm-8 ">
                            <h3><a href="blogdetail.php">Creative business to takeover the market</a></h3>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                            <a href="blogdetail.php" class="more">Read More</a>
                            </div>
  </div>
  <!-- blog list -->


  <!-- blog list -->
  <div class="row">
                            <div class="col-lg-4 col-sm-4 "><a href="blogdetail.php" class="thumbnail"><img src="images/blog/3.jpg" alt="blog title"></a></div>
                            <div class="col-lg-8 col-sm-8 ">
                            <h3><a href="blogdetail.php">Creative business to takeover the market</a></h3>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                            <a href="blogdetail.php" class="more">Read More</a>
                            </div>
  </div>
  <!-- blog list -->




  </div>
  <div class="col-lg-4 visible-lg">

  <!-- tabs -->
  <div class="tabbable">
              <ul class="nav nav-tabs">
                <li class=""><a href="#tab1" data-toggle="tab">Recent Post</a></li>
                <li class=""><a href="#tab2" data-toggle="tab">Most Popular</a></li>
                <li class="active"><a href="#tab3" data-toggle="tab">Most Commented</a></li>
              </ul>
              <div class="tab-content">
                <div class="tab-pane" id="tab1">
                  <ul class="list-unstyled">
                  <li>
                  <h5><a href="blogdetail.php">Real estate marketing growing</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>
                             <li>
                  <h5><a href="blogdetail.php">Real estate marketing growing</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>
                             <li>
                  <h5><a href="blogdetail.php">Real estate marketing growing</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>
                            </ul>
                </div>
                <div class="tab-pane" id="tab2">
                <ul  class="list-unstyled">
                  <li>
                  <h5><a href="blogdetail.php">Market update on new apartments</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>

                  <li>
                  <h5><a href="blogdetail.php">Market update on new apartments</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>

                  <li>
                  <h5><a href="blogdetail.php">Market update on new apartments</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>
                            </ul>
                </div>
                <div class="tab-pane active" id="tab3">
                <ul class="list-unstyled">
                            <li>
                  <h5><a href="blogdetail.php">Creative business to takeover the market</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>

                            <li>
                  <h5><a href="blogdetail.php">Creative business to takeover the market</a></h5>
                            <div class="info">Posted on: Jan 20, 2013</div>
                            </li>
                            </ul>
                </div>
              </div>



            </div>
  <!-- tabs -->

  </div>
</div>
</div>
</div>


{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- banner -->
<div class="inside-banner">
  <div class="container">
    <span class="pull-right"><a href="#">Home</a> / Contact Us</span>
    <h2>Contact Us</h2>
</div>
</div>
<!-- banner -->


<div class="container">
<div class="spacer">
<div class="row contact">
  <div class="col-lg-6 col-sm-6 ">


                <input type="text" class="form-control" placeholder="Full Name">
                <input type="text" class="form-control" placeholder="Email Address">
                <input type="text" class="form-control" placeholder="Contact Number">
                <textarea rows="6" class="form-control" placeholder="Message"></textarea>
      <button type="submit" class="btn btn-success" name="Submit">Send Message</button>




        </div>
  <div class="col-lg-6 col-sm-6 ">
  <div class="well"><iframe width="100%" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Pulchowk,+Patan,+Central+Region,+Nepal&amp;aq=0&amp;oq=pulch&amp;sll=37.0625,-95.677068&amp;sspn=39.371738,86.572266&amp;ie=UTF8&amp;hq=&amp;hnear=Pulchowk,+Patan+Dhoka,+Patan,+Bagmati,+Central+Region,+Nepal&amp;ll=27.678236,85.316853&amp;spn=0.001347,0.002642&amp;t=m&amp;z=14&amp;output=embed"></iframe></div>
  </div>
</div>
</div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="">
    <div id="slider" class="sl-slider-wrapper">
        <div class="sl-slider">

            {% for property in carousel_property_list %}
                <div class="sl-slide" data-orientation="horizontal" data-slice1-rotation="-25" data-slice2-rotation="-25" data-slice1-scale="2" data-slice2-scale="2">
                    <div class="sl-slide-inner">
                        <div class="bg-img bg-img-1"></div>
                        <h2><a href="{% url 'property:detail' property.id %}">{{ property.name }}</a></h2>
                        <blockquote>
                            <p class="location"><span class="glyphicon glyphicon-map-marker"></span> {{ property.location }}</p>
                            <p>{{ property.description }}</p>
                            <cite>$ {{ property.price }}</cite>
                        </blockquote>
                    </div>
                </div>
            {% endfor %}

        </div><!-- /sl-slider -->



        <nav id="nav-dots" class="nav-dots">
          <span class="nav-dot-current"></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </nav>

      </div><!-- /slider-wrapper -->
</div>



<div class="banner-search">
  <div class="container">
    <!-- banner -->
    <h3>Buy, Sale & Rent</h3>
    <div class="searchbar">
      <div class="row">
        <div class="col-lg-6 col-sm-6">
          <form method="get" action="{% url 'property:list' %}">
              <input type="text" class="form-control" name="name" placeholder="Search for Properties">
          <div class="row">
            <div class="col-lg-3 col-sm-3 ">
              <select class="form-control" name="building_type">
                  {% for type in property_building_type_list %}
                      <option value="{{ type.id }}">{{ type.name }}</option>
                  {% endfor %}
              </select>
            </div>
            <div class="col-lg-3 col-sm-4">
              <input type="number" name="min"class="form-control" placeholder="Minimum price" >
            </div>
            <div class="col-lg-3 col-sm-4">
                <input type="number" name="max" class="form-control" placeholder="Maximum price">
              </div>
              <div class="col-lg-3 col-sm-4">
                <button class="btn btn-success" type="submit" onclick="">Find Now</button>
              </div>
          </div>

          </form>

        </div>
        <div class="col-lg-5 col-lg-offset-1 col-sm-6 ">

            {% if not request.user.is_authenticated %}
                <p>Join now and get updated with all the properties deals.</p>
                <button class="btn btn-info"   data-toggle="modal" data-target="#loginpop">Login</button>
            {% else %}
                <button class="btn btn-info"><a href="{% url 'property:create' %}">Register Property</a> </button>
            {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
<!-- banner -->
<div class="container">
  <div class="properties-listing spacer"> <a href="{% url 'property:list' %}" class="pull-right viewall">View All Listing</a>
    <h2>Featured Properties</h2>
    <div id="owl-example" class="owl-carousel">
        {% for property in hot_property_list %}
            <div class="properties">
                <div class="image-holder"><img src="{{ MEDIA_URL }}{{ property.picture_1 }}" class="img-responsive" alt="{{ property.name }}"/>
                    <div class="status sold">
                        {% if property.availability %}
                            Available
                        {% else %}
                            Sold
                        {% endif %}
                    </div>
                </div>
                <h4><a href="{% url 'property:detail' property.id %}">{{ property.name }}</a></h4>
                <p class="price">Price: $ {{ property.price }}</p>
                <div class="listing-detail">
                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Bed Room">{{ property.bedrooms }}</span>
                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Living Room">{{ property.living_rooms }}</span>
                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Parking">{{ property.parking }}</span>
                    <span data-toggle="tooltip" data-placement="bottom" data-original-title="Kitchen">{{ property.kitchens }}</span>
                </div>
            <a class="btn btn-primary" href="{% url 'property:detail' property.id %}">View Details</a>
        </div>
        {% endfor %}
    </div>
  </div>
  <div class="spacer">
    <div class="row">
      <div class="col-lg-6 col-sm-9 recent-view">
        <h3>About Us</h3>
        <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.<br><a href="about.php">Learn More</a></p>

      </div>
      <div class="col-lg-5 col-lg-offset-1 col-sm-3 recommended">
        <h3>Recommended Properties</h3>
        <div id="myCarousel" class="carousel slide">
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1" class=""></li>
            <li data-target="#myCarousel" data-slide-to="2" class=""></li>
            <li data-target="#myCarousel" data-slide-to="3" class=""></li>
          </ol>
          <!-- Carousel items -->
          <div class="carousel-inner">
              {% for property in recommended_property_list %}
                  <div class="item active">
                    <div class="row">
                      <div class="col-lg-4">
                            <img src="{{ MEDIA_URL }}{{ property.picture_1 }}" class="img-responsive" alt="{{ property.name }}"/>
                        </div>
                        <div class="col-lg-8">
                            <h5><a href="{% url 'property:detail' property.id %}">{{ property.name }}</a></h5>
                            <p class="price">${{ property.price }}</p>
                            <a href="{% url 'property:detail' property.id %}" class="more">More Detail</a>
                        </div>
                    </div>
                  </div>
              {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}